version: "3.8"
name: aims

services:
  enrollment_db:
    image: postgres:latest
    container_name: enrollment_db
    environment:
      - POSTGRES_DB=enrollments
      - POSTGRES_USER=aims
      - POSTGRES_PASSWORD=aims
    ports:
      - "5432:5432"
    volumes:
      - enrollment:/var/lib/postgresql/data

  schedule_ms:
    build: .
    image: aims_schedule_ms
    container_name: schedule_ms
    depends_on:
      - enrollment_db
    links:
      - enrollment_db
    environment:
      - PORT=4000
      - DB_HOST=enrollment_db
      - DB_PORT=5432
      - DB_USER=aims
      - DB_PASS=aims
      - DB_NAME=enrollments
    ports:
      - "4001:4000"

volumes:
  enrollment:
